### ISSUE TITLE
Forge服务端安装后，偶尔出现ClientBoundPacket错误

### ISSUE THREAD

**Issue by ccpemily** [0999312/SlashBlade_Resharped#12]
1.20.1-Forge服务端安装SBR后，两个玩家若靠得较近，几分钟（1-10不等）后就会有玩家因网络包错误：Error Receiving packet 85掉线，报错原因为ClientBoundSetEquipmentPacket调用的toNBT方法出现CME空指针，此处的Mixin代码仅有SBR（已逐个排查mod，问题发生在加入SBR之后）

单人模式、服务器仅有一名玩家、玩家间距离较远（互相不在视距内）时，不会触发此问题
![QQ截图20240611011138](https://github.com/0999312/SlashBlade_Resharped/assets/56390205/73faab59-e3f1-4604-8853-38949dbba6fb)

**Comment by ccpemily** [comment]
未能在本地服务端复现，可能是云服务器跟拔刀剑八字不合。sad

**Comment by ccpemily** [comment]
成功在本地服务器上复现，挂机时间长达1小时。。目前正在测试到底是哪个Mod和拔刀剑冲突了，Modlist见图
![image](https://github.com/0999312/SlashBlade_Resharped/assets/56390205/d52fb32e-9e84-4db7-9abf-10236312d65f)
![UCCT)_)$0({O{CUH@LCMYD](https://github.com/0999312/SlashBlade_Resharped/assets/56390205/ed5fb892-aff8-4898-b475-ffc5d57d742f)

**Comment by 0999312** [comment]
能否提供一下安装connectivity模组之后的日志文件以便我们进行排错。

**Comment by ccpemily** [comment]
晚点下班回来查查看，感谢关注

**Comment by ccpemily** [comment]
安装Connectivity后，本地服务器不再出现掉线问题。

**Comment by ccpemily** [comment]
云服务器上仍然报错：https://mclo.gs/W7WkEEU

**Comment by 0999312** [comment]
请测试一下0.5.9版本是否还会出现此类BUG
