### ISSUE TITLE
合成表兼容问题

### ISSUE THREAD

**Issue by shardflower** [0999312/SlashBlade_Resharped#13]
对于EMI与JEI同时使用的情况，JEI在被隐藏的情况下，EMI无法正确显示合成表
![image](https://github.com/0999312/SlashBlade_Resharped/assets/138157740/0ef12cf1-0787-46fb-9edd-c486c24f7ae5)

**Comment by 0999312** [comment]
很抱歉，我们对此目前暂时无能为力。

**Comment by 0999312** [comment]
已经在1.0.2中修复。
