### ISSUE TITLE
在部分显卡环境（存疑）下，所有拔刀剑物品与手持模型渲染为黑色

### ISSUE THREAD

**Issue by HappyRespawnanchor** [0999312/SlashBlade_Resharped#18]
测试环境：
![图片](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/651bd7c2-19d7-4002-908c-311ccc20d4e8)
![图片](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/3e8ba581-47f5-4cf5-be64-dc89a8ad2a97)
已有多名玩家反馈此问题，似乎与显卡环境（存疑）有关：
![图片](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/99986012-dce1-41b7-afa3-df4e8797d0e6)
![EDA440B4-6071-4DB8-A238-1D4A6F192F16](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/97918118-0446-4a6c-89c3-92d926ae033d)

![图片](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/f47befcd-2a49-4c3a-898a-f32346a96137)
![图片](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/7d4af6bd-9153-4632-9c60-f03765b4c4aa)
![图片](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/98a007c0-cdaf-4c35-929f-e34f8427327a)
![图片](https://github.com/0999312/SlashBlade_Resharped/assets/80967824/463ce239-320e-4c85-bb02-604dba2ed715)

**Comment by AK16bit** [comment]
这似乎是原版拔刀剑就存在的bug了

**Comment by freeze-dolphin** [comment]
A770 16g, 以及核显均无法正常渲染材质 :cry: 
![2024-10-06_14 56 48](https://github.com/user-attachments/assets/95374a5c-f204-4c80-87d3-0328c1c31bd8)
![2024-10-06_15 09 28](https://github.com/user-attachments/assets/b4c9b554-6f1b-4968-801f-a2eb221d9fe0)

**Comment by freeze-dolphin** [comment]
解决方法:

将 `BladeRenderState.java` 文件里这一段中的注释取消，然后重新编译即可
https://github.com/0999312/SlashBlade_Resharped/blob/e6817113b5a438f9339acc54320ef1dc508b49fc/src/main/java/mods/flammpfeil/slashblade/client/renderer/util/BladeRenderState.java#L52-L62

![image](https://github.com/user-attachments/assets/63079fe8-4490-4ba9-a30f-1062bfd05520)

**由于不清楚作者对此行代码进行注释的原因，这么做可能导致其他问题发生**

Build: [SlashBladeResharped-1.20.1-1.0.2.jar.zip](https://github.com/user-attachments/files/17269149/SlashBladeResharped-1.20.1-1.0.2.jar.zip)

**Comment by HappyRespawnanchor** [comment]
> 解决方法:
> 
> 
> 
> 将 `BladeRenderState.java` 文件里这一段中的注释取消，然后重新编译即可
> 
> https://github.com/0999312/SlashBlade_Resharped/blob/e6817113b5a438f9339acc54320ef1dc508b49fc/src/main/java/mods/flammpfeil/slashblade/client/renderer/util/BladeRenderState.java#L52-L62
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/63079fe8-4490-4ba9-a30f-1062bfd05520)
> 
> 
> 
> **由于不清楚作者对此行代码进行注释的原因，这么做可能导致其他问题发生**
> 
> 
> 
> 构建结果 (解压出 .jar 后使用): [SlashBladeResharped-1.20.1-1.0.2.jar.zip](https://github.com/user-attachments/files/17269188/SlashBladeResharped-1.20.1-1.0.2.jar.zip)
> 
> 

可以用mixin注入这个方法的末尾加上这两行代码做修复补丁

**Comment by freeze-dolphin** [comment]
> 可以用 mixin 注入这个方法的末尾加上这两行代码做修复补丁 

我没写过模组 :sob: 
如果有空的话可以帮忙搞一个吗 (我看各平台最新版是 1.0.3, 但是仓库的 master 分支还是 1.0.2), 这样就能在最新版正常渲染了 :smile:

**Comment by HappyRespawnanchor** [comment]
> > 可以用 mixin 注入这个方法的末尾加上这两行代码做修复补丁 
> 
> 
> 
> 我没写过模组 :sob: 
> 
> 如果有空的话可以帮忙搞一个吗 (我看各平台最新版是 1.0.3, 但是仓库的 master 分支还是 1.0.2), 这样就能在最新版正常渲染了 :smile: 

我尽量

**Comment by HappyRespawnanchor** [comment]
> > 可以用 mixin 注入这个方法的末尾加上这两行代码做修复补丁 
> 
> 
> 
> 我没写过模组 :sob: 
> 
> 如果有空的话可以帮忙搞一个吗 (我看各平台最新版是 1.0.3, 但是仓库的 master 分支还是 1.0.2), 这样就能在最新版正常渲染了 :smile: 

https://github.com/HappyRespawnanchor/Resharped_RenderFix_Patch
还没搞好，我对mixin不是特别熟，在研究怎么末尾插入代码

**Comment by HappyRespawnanchor** [comment]
> > 可以用 mixin 注入这个方法的末尾加上这两行代码做修复补丁 
> 
> 
> 
> 我没写过模组 :sob: 
> 
> 如果有空的话可以帮忙搞一个吗 (我看各平台最新版是 1.0.3, 但是仓库的 master 分支还是 1.0.2), 这样就能在最新版正常渲染了 :smile: 

几乎完工了，但是因为乱七八糟的原因没法加载（不是代码的原因），我明天修下应该就好了

**Comment by HappyRespawnanchor** [comment]
> > 可以用 mixin 注入这个方法的末尾加上这两行代码做修复补丁
> 
> 我没写过模组 😭 如果有空的话可以帮忙搞一个吗 (我看各平台最新版是 1.0.3, 但是仓库的 master 分支还是 1.0.2), 这样就能在最新版正常渲染了 😄

![图片](https://github.com/user-attachments/assets/07921d64-a986-429d-8d4d-f4dabbb455db)
完工，可以使用了，已发github release，你试试用下

**Comment by HappyRespawnanchor** [comment]
> 解决方法:
> 
> 
> 
> 将 `BladeRenderState.java` 文件里这一段中的注释取消，然后重新编译即可
> 
> https://github.com/0999312/SlashBlade_Resharped/blob/e6817113b5a438f9339acc54320ef1dc508b49fc/src/main/java/mods/flammpfeil/slashblade/client/renderer/util/BladeRenderState.java#L52-L62
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/63079fe8-4490-4ba9-a30f-1062bfd05520)
> 
> 
> 
> **由于不清楚作者对此行代码进行注释的原因，这么做可能导致其他问题发生**
> 
> 
> 
> 构建结果 (解压出 .jar 后使用): [SlashBladeResharped-1.20.1-1.0.2.jar.zip](https://github.com/user-attachments/files/17269188/SlashBladeResharped-1.20.1-1.0.2.jar.zip)
> 
> 

不过挂刀台还是黑的，你有什么头猪吗

**Comment by freeze-dolphin** [comment]
> 不过挂刀台还是黑的，你有什么头猪吗

刀挂台是正常的，他的材质就是这样

**Comment by 0999312** [comment]
请更新至1.1.5检查还有无该BUG

**Comment by HappyRespawnanchor** [comment]
![图片](https://github.com/user-attachments/assets/ef51f5ea-019b-4556-a951-3c0cf181c7b3)
![图片](https://github.com/user-attachments/assets/20e564ff-33ac-43ba-80ea-4a9ce9762ec1)
已确认修复，感谢作者
