### ISSUE TITLE
[BUG] 耀魂数与杀敌数的数值错误

### ISSUE THREAD

**Issue by AK16bit** [0999312/SlashBlade_Resharped#19]
**在主手与副手的同类拔刀剑的耀魂数/杀敌数不一致时，主手拔刀剑会同步副手拔刀剑的耀魂数/杀敌数。**
**已知与附魔、SA差异无关。**
    forge版本：47.3.3
    mod版本：1.20.1-0.6.0
    模组列表：jei-1.20.1-forge-15.3.0.8、SlashBladeResharped-1.20.1-0.6.0、bendy-lib-forge-4.0.0、player-animation-lib-forge-1.0.2-rc1+1.20

**复刻步骤**
    1.准备两把耀魂数/杀敌数不一样的同类拔刀剑
        如 A：白狐（耀魂数：114），B：白狐（耀魂数：514）
    2.将A拔刀剑放置到hotbar的第一格并手持着
    3.将B拔刀剑从物品栏中放置到副手栏
    4.观察两把拔刀剑的耀魂数/杀敌数

**Comment by Arcomit** [comment]
补充，只是显示BUG，挪动主手拔刀或丢出再捡起会恢复原样，初步判断是ActiveState导致的
