### ISSUE TITLE
为什么 加了山樱附属 贴图不显示 物品栏也没有 只有成就

### ISSUE THREAD

**Issue by windy664** [0999312/SlashBlade_Resharped#20]
https://www.mcmod.cn/class/2843.html

![image](https://github.com/user-attachments/assets/10d82bca-0b05-4f6e-9bbd-cdaf2ff236cc)
![image](https://github.com/user-attachments/assets/9c6cd5c4-672d-4fb3-91e8-d14686a105e5)

**Comment by 0999312** [comment]
本模组不支持拔刀剑2的附属包。
