### ISSUE TITLE
服务器使用拔刀剑，客户端崩溃

### ISSUE THREAD

**Issue by FaiDreaM-FD** [0999312/SlashBlade_Resharped#24]
[crash-2024-08-10_16.40.26-client.txt](https://github.com/user-attachments/files/16569005/crash-2024-08-10_16.40.26-client.txt)
客户端崩溃报告附上，请问是什么环节出现问题？所使用的服务端为arclight-forge-1.20.1-1.0.5

**Comment by Arcomit** [comment]
如果自己添加了新的拔刀或更换了模型，可以尝试检查模型是否按格式分层，路径名称是否正确

**Comment by FaiDreaM-FD** [comment]
> 如果自己添加了新的拔刀或更换了模型，可以尝试检查模型是否按格式分层，路径名称是否正确

没有添加，服务器有关拔刀剑的内容只有拔刀剑：重锋本体，并未对其进行过修改，版本是0.7.3

**Comment by Arcomit** [comment]
> > 如果自己添加了新的拔刀或更换了模型，可以尝试检查模型是否按格式分层，路径名称是否正确
> 
> 没有添加，服务器有关拔刀剑的内容只有拔刀剑：重锋本体，并未对其进行过修改，版本是0.7.3

能否提供一个复现该情况的具体流程？

**Comment by FaiDreaM-FD** [comment]
> > > 如果自己添加了新的拔刀或更换了模型，可以尝试检查模型是否按格式分层，路径名称是否正确
> > 
> > 
> > 没有添加，服务器有关拔刀剑的内容只有拔刀剑：重锋本体，并未对其进行过修改，版本是0.7.3
> 
> 能否提供一个复现该情况的具体流程？

我不清楚是不是其他mod影响到了拔刀剑：重锋，但是在单人档游玩是不会出现这个问题的，只在服务器的时候，只尝试了木偶，在耐久度归0的时候应该是会掉落到地上，但是耐久度归0 的那一刻就会崩掉客户端，服务器后台没有任何反馈

**Comment by FaiDreaM-FD** [comment]
https://pastebin.com/ix9jdTrv
附上服务器所有mod列表，刚刚尝试过，铁刀木也不可以，似乎是在耐久度归0的时候应该爆出的耀魂碎片出现错误了

**Comment by Arcomit** [comment]
加个非空判断应该能解决问题，但我检查了相关代码会出现NULL挺令人感到诧异的

**Comment by FaiDreaM-FD** [comment]
> 加个非空判断应该能解决问题，但我检查了相关代码会出现NULL挺令人感到诧异的

那只能等后续修复吗？现在只能偷摸一个人玩了:(

**Comment by Arcomit** [comment]
> > 加个非空判断应该能解决问题，但我检查了相关代码会出现NULL挺令人感到诧异的
> 
> 那只能等后续修复吗？现在只能偷摸一个人玩了:(

我并不是妖怪之山小组的成员，不过我提交了PR，我不确信这是否有效，因为我无法在arclight端下复现这个问题。

**Comment by FaiDreaM-FD** [comment]
> > > 加个非空判断应该能解决问题，但我检查了相关代码会出现NULL挺令人感到诧异的
> > 
> > 
> > 那只能等后续修复吗？现在只能偷摸一个人玩了:(
> 
> 我并不是妖怪之山小组的成员，不过我提交了PR，我不确信这是否有效，因为我无法复现这个问题。

感谢:)
