### ISSUE TITLE
[BUG]JEI无法正确展示拔刀剑

### ISSUE THREAD

**Issue by somerui** [0999312/SlashBlade_Resharped#27]
Minecraft 1.20.1 Forge 47.3.7,SlashBlade Reshraped 1.0.1,Just Enough Items 15.17.0.76
使用JEI查看拔刀剑会全部变成"无铭[无名]",但创造模式物品栏无问题。
推测可能是拔刀剑全部共用一个id"slashblade:slashblade"而新版本JEI出了什么问题导致JEI无法读取拔刀剑的NBT导致的。

**Comment by 0999312** [comment]
已经于1.0.2版本中修复。
