### ISSUE TITLE
使用AMD显卡时，刀刃纹理在物品栏和手中显示为黑色

### ISSUE THREAD

**Issue by 4g1t0** [0999312/SlashBlade_Resharped#28]
![image](https://github.com/user-attachments/assets/128efa74-2207-456e-89d4-eb54162b765d)

**Comment by freeze-dolphin** [comment]
#18

**Comment by HappyRespawnanchor** [comment]
尝试使用补丁修复：https://github.com/HappyRespawnanchor/Resharped-RenderFix-Patch

**Comment by 0999312** [comment]
请更新至1.1.5检查还有无该BUG

**Comment by HappyRespawnanchor** [comment]
![图片](https://github.com/user-attachments/assets/247543a1-dacd-4e62-9e70-b02723363ec3)
![图片](https://github.com/user-attachments/assets/ad744205-da9d-41ff-b064-77bee67dcf39)
我这边已经确认1.1.5版本修复

**Comment by freeze-dolphin** [comment]
所以有人能解释一下为什么缺了一行代码却能在Intel核显上正常运行🐴

**Comment by HappyRespawnanchor** [comment]
> 所以有人能解释一下为什么缺了一行代码却能在Intel核显上正常运行🐴

我也觉得很神奇，一个会在特定设备上导致渲染问题的bug
但是直到解决都没人查出根本的深层原因（大概）

**Comment by 0999312** [comment]
> 所以有人能解释一下为什么缺了一行代码却能在Intel核显上正常运行🐴

本质原因是拔刀剑渲染的一些强制性操作没有执行。
而且很没有必要的操作，所以重写一下就可以解决。
