### ISSUE TITLE
在使用部分特殊幻影剑会导致游戏未响应与使用幻影剑会导致FTBEss模组的传送指令失效

### ISSUE THREAD

**Issue by Lonmo0208** [0999312/SlashBlade_Resharped#30]
游戏版本1.20.1
模组版本1.0.2~1.0.3都出现过
本人觉得其他可能影响的模组：YSM 现代化UI 

触发过程主副手两把 幸圣刃
按住shift+w+a+d+鼠标中键触发幻影剑然后加鼠标右键触发SA后
游戏会突然未响应
观察日志并无报错....
下面是在加入服务器后开始测试到游戏未响应输出的日志 （是的没有报错）
[12:43:17] [Render thread/INFO] [minecraft/ChatComponent]: [System] [CHAT] *** 已成功登录 ***
[12:43:17] [Render thread/INFO] [Gamemode Overhaul/]: Client commands registered!
[12:43:17] [Render thread/INFO] [co.te.re.Redirector/]: Redirecting net/minecraftforge/client/extensions/common/IClientItemExtensions$FontContext
[12:43:36] [Render thread/INFO] [co.te.re.Redirector/]: Redirecting top/theillusivec4/caelus/api/CaelusApi$TriState
观察日志发现，虽然游戏未响应，但是还是在正常运行... 
（因为我看到几分钟后我的内存清理模组还在输出日志）
第二个错误问题
在使用鼠标中键触发幻影剑 
不管是什么 都会导致FTBEss的任意有关于的传送的指令无效
比如/back啊/warp啊/tpa啊 都会让玩家无法传送
玩家死亡一次后正常...
(后台未遇见报错....)
模组列表：
![MODLIST](https://github.com/user-attachments/assets/f9c47217-607f-4d32-89d7-cee75dba9761)

**Comment by Lonmo0208** [comment]
[MODz.zip](https://github.com/user-attachments/files/17125270/MODz.zip)
这是里面有4个模组是本人修改？也不算修改就是版本识别改成1.20可以加载后的模组

**Comment by Quarkrus** [comment]
I think it's a rendering problem with rubidium, try using embeddium (It is best to use the stable version 0.3.17), it's more suitable for large modpacks
![image](https://github.com/user-attachments/assets/1aa99416-efa8-4a72-8e9a-88c30d2f71ce)
我認為是銣的渲染問題，嘗試使用embeddium（最好使用穩定版本0.3.17），它更適合大型modpack

**Comment by Lonmo0208** [comment]
> 我觉得是铷的渲染问题，试试用embeddium（最好用稳定版本0.3.17），它更适合大型的modpack ![图像](https://private-user-images.githubusercontent.com/175550013/371834637-1aa99416-efa8-4a72-8e9a-88c30d2f71ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDQzOTgsIm5iZiI6MTcyNzYwNDA5OCwicGF0aCI6Ii8xNzU1NTAwMTMvMzcxODM0NjM3LTFhYTk5NDE2LWVmYTgtNGE3Mi04ZTlhLTg4YzMwZDJmNzFjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMDAxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWE0NGQxODU1MTIwYTEzNTA0MTJlYjFiMjE2MGYxYjAzMTBiODRmYjk4Mzc4ZWVmYWQ1Y2QwMzlhYTE1MDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0k7-biSGh2E11WCG7zuzOSPhbB4lldOv1QcshHHkGsw) 我認為是銣的渲染問題，嘗試使用embeddium（最好使用穩定版本0.3.17），它更適合大型modpack

我一直都是使用embeddium 我去试试您推荐的版本

**Comment by Lonmo0208** [comment]
> 我觉得是铷的渲染问题，试试用embeddium（最好用稳定版本0.3.17），它更适合大型的modpack ![图像](https://private-user-images.githubusercontent.com/175550013/371834637-1aa99416-efa8-4a72-8e9a-88c30d2f71ce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MDQzOTgsIm5iZiI6MTcyNzYwNDA5OCwicGF0aCI6Ii8xNzU1NTAwMTMvMzcxODM0NjM3LTFhYTk5NDE2LWVmYTgtNGE3Mi04ZTlhLTg4YzMwZDJmNzFjZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxMDAxMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWE0NGQxODU1MTIwYTEzNTA0MTJlYjFiMjE2MGYxYjAzMTBiODRmYjk4Mzc4ZWVmYWQ1Y2QwMzlhYTE1MDU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0k7-biSGh2E11WCG7zuzOSPhbB4lldOv1QcshHHkGsw) 我認為是銣的渲染問題，嘗試使用embeddium（最好使用穩定版本0.3.17），它更適合大型modpack

并不行qwq
