### ISSUE TITLE
[BUG] EMI中鼠标经过后会显示无名

### ISSUE THREAD

**Issue by IM2eR0** [0999312/SlashBlade_Resharped#31]
测试环境：1.20.1
问题详细描述：安装了 EMI 与 JEI（两者可以共存，JEI会为EMI提供合成表），在首次启动游戏可以在EMI中看见对应拔刀剑的材质，合成表正常显示，但鼠标经过对应的拔刀剑上后，材质与名称均会变为 无名

可能相关的MOD：
jei-1.20.1-forge-15.16.2.73.jar
[拔刀剑：重锋] SlashBladeResharped-1.20.1-1.0.3.jar
[拔刀剑日系附属包] SJAP_Resharpened-1.20.1-1.0.5.jar
emi-1.1.13+1.20.1+forge.jar
emiffect-forge-1.1.2+mc1.20.1.jar
emi-letsdo-compat-1.3.jar
EMIEnchants-forge-1.19.3-1.20.4-1.0.0.jar
emi_loot-0.7.3+1.20.1+forge.jar
[EMI村民交易] emitrades-forge-1.2.1+mc1.20.1.jar

![图片](https://github.com/user-attachments/assets/9e40c48b-5c80-4d52-a05e-76797184500e)
![图片](https://github.com/user-attachments/assets/bdd493b9-1fbe-49ed-9d82-7344c21eb70d)
![图片](https://github.com/user-attachments/assets/d7f0855e-ec88-48c2-a3f4-093f0ebd1214)

**Comment by IM2eR0** [comment]
补充，JEI曾尝试过更新至最新版，问题依旧

**Comment by 0999312** [comment]
无法复现具体BUG

**Comment by IM2eR0** [comment]
我用的是服务器，会不会和这个有关系？

**Comment by 0999312** [comment]
已经做过双端测试
开发端没有相关bug，也没有日志文件
在其他人的服务器上出现过但没有日志可以追溯。

**Comment by 0999312** [comment]
已在1.1.9当中修复此问题。
