### ISSUE TITLE
该模组的拔刀剑攻击Alex的洞穴的生物会产生崩溃

### ISSUE THREAD

**Issue by StarPrimary** [0999312/SlashBlade_Resharped#33]
版本 1.20.1 1.1.6
日志如下
[crash-2024-10-13_12.23.20-server.txt](https://github.com/user-attachments/files/17353139/crash-2024-10-13_12.23.20-server.txt)

**Comment by StarPrimary** [comment]
补充 用幻影剑和sa打暮色的娜迦也会崩溃
日志如下
[crash-2024-10-13_12.50.31-server.txt](https://github.com/user-attachments/files/17353195/crash-2024-10-13_12.50.31-server.txt)

**Comment by 0999312** [comment]
已经在1.1.7和SJAP最新版中修复，请及时更新。
