### ISSUE TITLE
拔刀剑在jei和暮色中的合成表bug

### ISSUE THREAD

**Issue by Doc3312** [0999312/SlashBlade_Resharped#48]
1、在jei合成表中，查询任意拔刀剑的合成方式和用途都会展现所有的拔刀剑合成方式，无法查到指定的拔刀剑；
2、在暮色森林的拆解台中，和第一条一样，任意一把拔刀剑都能被拆解成相关合成表的所有拔刀剑
版本：Forge1.20.1；

mod都是最新版本
重锋：1.1.9；
jei：15.20.0.104；
暮色：4.3.2508

【如图，一把鄂门可以直接拆成绿乃雾】

![2024-11-18_15 39 13](https://github.com/user-attachments/assets/eccc7d3a-3948-4580-bc47-493e0ead616a)
![2024-11-18_15 39 25](https://github.com/user-attachments/assets/d0ce9bae-7432-4c03-b8e5-8e1fb06cd7a9)
![2024-11-18_15 39 26](https://github.com/user-attachments/assets/14597d6e-7bb4-407f-863e-8f61881cb446)
![2024-11-18_15 39 29](https://github.com/user-attachments/assets/fc2c4ed3-6d48-40c6-908e-9669c6ab1cc3)
![2024-11-18_15 39 35](https://github.com/user-attachments/assets/a2f0b244-fe17-4f06-8327-3de9f9c50af5)

**Comment by Doc3312** [comment]
补充bug：
1、从jei中拿取的拔刀剑会直接变成无铭刀。
2、在精妙背包的虚空升级中，一旦放入拔刀剑，所有拔刀剑都会被默认删除而不是只删除被放入的拔刀剑
【精妙背包版本3.20.11.1115】

**Comment by 0999312** [comment]
在1.1.14中已经尽可能修复，请检查是否还有此现象。
