### ISSUE TITLE
JEI合成表界面不显示前置刀的耀魂数、杀敌数、精炼数

### ISSUE THREAD

**Issue by mc-kaishixiaxue** [0999312/SlashBlade_Resharped#53]
模组版本：1.20.1-1.1.11
JEI版本：1.20.1-forge-15.20.0.105
以无铭（早期拔刀剑的大太刀）+8宝珠合成村正为例，查看村正的合成表时，合成所用的无铭没有显示耀魂数、杀敌数、精炼数，但这把无铭却需同时满足两个条件：耀魂数≥10,000，精炼数≥20。该漏洞会让玩家以为这把无铭不用满足任何条件就能合成村正，造成误导。
”前置刀“在[百科](https://www.mcmod.cn/item/462197.html)的介绍

**Comment by 102637759j** [comment]
從 jei-1.20.1-forge-15.17.0.74.jar就不能顯示，jei-1.20.1-forge-15.17.0.73.jar還正常运作，而且没有查不到特定刀的問题(查刀的合成表，會顯示所有刀的合成表，而不是你想查的刀).

https://www.dropbox.com/scl/fi/ji8qykbk9af18mu95jqsa/Slashblade-Jei-bug.mp4?rlkey=z1sa23mwnoouuj9m1g1bdgskr&st=xwywdqpn&dl=0

**Comment by 0999312** [comment]
已经在1.1.13版本当中修复，请确认是否还存在相关BUG

**Comment by 102637759j** [comment]
Slashblade - 1.1.13 在 Jei_105 還是不能顯示
附上影片:
https://www.dropbox.com/scl/fi/onwdrwnbbqfr0s2z02946/Jei_105.mp4?rlkey=xrxcnnigbio2s0jxiqh8654tx&st=2g083hw4&dl=0

**Comment by 102637759j** [comment]
@0999312 暮光的解合台也沒有改, 只更新了Just Judgement cut 的傷害調正
https://www.dropbox.com/scl/fi/n9p4pe8a9nbliotfx15d6/1.1.13.mp4?rlkey=5w8qt0ryflullq7a253lpevwx&st=5dpbjuhx&dl=0

**Comment by 0999312** [comment]
> @0999312 暮光的解合台也沒有改, 只更新了Just Judgement cut 的傷害調正 https://www.dropbox.com/scl/fi/n9p4pe8a9nbliotfx15d6/1.1.13.mp4?rlkey=5w8qt0ryflullq7a253lpevwx&st=5dpbjuhx&dl=0

暮光森林的BUG無法修復，十分抱歉

**Comment by 102637759j** [comment]
現在Jei 的問題是更新了還沒有 Merge 嗎？還是沒修好？

**Comment by 102637759j** [comment]
> 暮光森林的BUG無法修復，十分抱歉
我以爲 #48 是指暮光的解合台問提

**Comment by 0999312** [comment]
在1.1.14中已经尽可能修复，请检查是否还有此现象。

**Comment by 102637759j** [comment]
1.1.14 已修复, 查的到特定刀與合成条件,也可以分開 Bookmark 了
