### ISSUE TITLE
发现一个幻影剑bug

### ISSUE THREAD

**Issue by chenyinlh** [0999312/SlashBlade_Resharped#6]
幻影剑箭矢在幻影剑特效消失后会卡住
![2024-05-29_21 31 13](https://github.com/0999312/SlashBlade_Resharped/assets/170898448/46cd25b1-6b4f-459d-aadc-9d9e6613d007)

**Comment by chenyinlh** [comment]
是由Shift+V锁敌冲刺时射出的幻影剑,也见过卡在空中的

**Comment by 0999312** [comment]
奇怪，幻影剑似乎不应该是箭矢？
