### ISSUE TITLE
日系附属重置兼容问题

### ISSUE THREAD

**Issue by imhuiyu** [0999312/SlashBlade_Resharped#9]
发现问题如下
拔刀剑重锋不能直接代替拔刀剑2，没法像拔刀2一样 与[拔刀剑日系附属重置版](https://www.mcmod.cn/class/13203.html)联动，但是可以正常进入游戏。
同时注意到，现在高版本 （1.16.5-1.20.1）的日系附属 并非妖怪之山锻刀铺团队制作，想询问日后是否会 做兼容性方面的更新 或者重新开发日系附属重置？

![1716471703_296533_pWNS](https://github.com/0999312/SlashBlade_Resharped/assets/118999198/dc707fed-547a-4aaf-8cc3-a720cc4d7709)
![1716471904_296533_YzLg](https://github.com/0999312/SlashBlade_Resharped/assets/118999198/d7747fe5-e24a-4860-ae17-6c042b16926e)

**Comment by 0999312** [comment]
日系附属包正在重新开发中，敬请期待。
